import os
import pandas as pd
import matplotlib.pyplot as plt
from typing import Any, Dict
from langchain_core.tools import tool
from langchain_experimental.utilities.python import PythonREPL
from app.core.config import settings

# Ensure output directory exists
OUTPUT_DIR = "output_figures"
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

class SecurePythonREPL:
    def __init__(self):
        self.repl = PythonREPL()

    def run(self, code: str) -> str:
        # Pre-execution checks or setup can go here
        return self.repl.run(code)

python_repl = SecurePythonREPL()

@tool
def analytics_sandbox(code: str, feedback: str = None) -> str:
    """
    A secure Python sandbox for data analysis and visualization.
    Use this to execute pandas, matplotlib, and numpy code.
    
    Guidelines:
    - You can read CSV and Excel files generated by other tools.
    - When creating plots, ALWAYS save them to the 'output_figures' directory using plt.savefig('output_figures/filename.png').
    - Do not try to show() plots as there is no GUI.
    - Focus on data analysis, summary statistics, and visualization.
    - Always print() the results you want to see.
    
    Args:
        code: The Python code to execute.
        feedback: Extra user considerations or specific constraints for the code execution.
    """
    try:
        # If feedback is provided, we can prepend it as a comment for context in the execution log
        # although its primary use is for the agent's prompt context.
        execution_code = code
        if feedback:
            execution_code = f"# User Feedback: {feedback}\n" + code
            
        result = python_repl.run(execution_code)
        return f"Execution Result:\n{result}"
    except Exception as e:
        return f"Error executing code: {str(e)}"
